services:
  # Backend FastAPI
  backend:
    build: ./backend
    container_name: sales-copilot-backend-v4.2.1
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/sales_copilot
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_API_URL=${OLLAMA_API_URL}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - SECRET_KEY=${SECRET_KEY}
      - APP_VERSION=v4.2.1
      - BACKEND_ARCHITECTURE=modular_session_orchestrator
      - FRONTEND_UI_FIXES=enabled
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - qdrant
    networks:
      - sales-copilot-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 

  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: sales-copilot-db-v4.2.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales_copilot
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - sales-copilot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: sales-copilot-qdrant-v4.2.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - sales-copilot-network
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React (dla development)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sales-copilot-frontend-v4.2.1
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
      - REACT_APP_WS_URL=ws://backend:8000/ws
      - NODE_ENV=development
      - DOCKER_ENV=true
      - REACT_APP_VERSION=v4.2.1
      - REACT_APP_FRONTEND_ARCHITECTURE=ultra_brain_v4.2.1
      - REACT_APP_ENABLE_ULTRA_BRAIN=true
      - REACT_APP_ENABLE_UI_FIXES=true
      - REACT_APP_DEBUG_DATA_FLOW=true
    networks:
      - sales-copilot-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
  qdrant_storage:

networks:
  sales-copilot-network:
    driver: bridge
