"""Add suggestion_id to feedback model for granular feedback

Revision ID: 18a87c48c7e5
Revises: 467f63d43050
Create Date: 2025-08-19 10:56:11.916669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a87c48c7e5'
down_revision: Union[str, Sequence[str], None] = '467f63d43050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('suggestion_id', sa.String(length=36), nullable=True, comment='ID ocenionej porady (quick_response lub suggested_action)'))
    op.create_index(op.f('ix_feedbacks_suggestion_id'), 'feedbacks', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_suggestion_id'), table_name='feedbacks')
    op.drop_column('feedbacks', 'suggestion_id')
    # ### end Alembic commands ###
