"""Add is_processed_for_learning to Feedback

Revision ID: 467f63d43050
Revises: 5c1cc9438e1c
Create Date: 2025-08-19 07:07:31.140843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467f63d43050'
down_revision: Union[str, Sequence[str], None] = '5c1cc9438e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('is_processed_for_learning', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_feedbacks_is_processed_for_learning'), 'feedbacks', ['is_processed_for_learning'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_is_processed_for_learning'), table_name='feedbacks')
    op.drop_column('feedbacks', 'is_processed_for_learning')
    # ### end Alembic commands ###
