"""add_tags_to_clients

Revision ID: 5b3a0b39c0cc
Revises: baa8c35b2dfd
Create Date: 2025-09-08 22:34:34.790622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b3a0b39c0cc'
down_revision: Union[str, Sequence[str], None] = 'baa8c35b2dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Lista tagów klienta'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'tags')
    # ### end Alembic commands ###
