"""Add prl_and_fds_scores_to_session

Revision ID: 5c1cc9438e1c
Revises: 087d2d0a6636
Create Date: 2025-08-19 06:25:02.679755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1cc9438e1c'
down_revision: Union[str, Sequence[str], None] = '087d2d0a6636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('prl_score', sa.Integer(), nullable=True, comment='Poziom Gotowości do Zakupu (0-100)'))
    op.add_column('sessions', sa.Column('fds_score', sa.Integer(), nullable=True, comment="Wskaźnik 'Fun Drivera' (0-100)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'fds_score')
    op.drop_column('sessions', 'prl_score')
    # ### end Alembic commands ###
