"""add_length_constraint_to_archetype

Revision ID: 99e0d9ff2396
Revises: 5b3a0b39c0cc
Create Date: 2025-09-08 23:35:57.950074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e0d9ff2396'
down_revision: Union[str, Sequence[str], None] = '5b3a0b39c0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
