"""Add PromptTemplate and Feedback models

Revision ID: baa8c35b2dfd
Revises: 5c1cc9438e1c
Create Date: 2025-09-08 06:33:31.408082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baa8c35b2dfd'
down_revision: Union[str, Sequence[str], None] = '5c1cc9438e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPERIMENTAL', 'ARCHIVED', name='promptstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=True)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.String(length=36), nullable=True, comment='ID ocenionej porady (quick_response lub suggested_action)'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Ocena: 1 (pozytywna) lub -1 (negatywna)'),
    sa.Column('feedback_type', sa.String(), nullable=True, comment='Typ feedbacku: quick_response, suggested_action, etc.'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Opcjonalny komentarz użytkownika'),
    sa.Column('is_processed_for_learning', sa.Integer(), nullable=False, comment='Czy feedback został przetworzony przez system uczenia'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_is_processed_for_learning'), 'feedbacks', ['is_processed_for_learning'], unique=False)
    op.create_index(op.f('ix_feedbacks_suggestion_id'), 'feedbacks', ['suggestion_id'], unique=False)
    op.drop_column('interactions', 'psychometric_analysis')
    op.drop_column('sessions', 'prl_score')
    op.drop_column('sessions', 'summary')
    op.drop_column('sessions', 'fds_score')
    op.drop_column('sessions', 'outcome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('fds_score', sa.INTEGER(), autoincrement=False, nullable=True, comment="Wskaźnik 'Fun Drivera' (0-100)"))
    op.add_column('sessions', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('prl_score', sa.INTEGER(), autoincrement=False, nullable=True, comment='Poziom Gotowości do Zakupu (0-100)'))
    op.add_column('interactions', sa.Column('psychometric_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_feedbacks_suggestion_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_is_processed_for_learning'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
